### ISSUE TITLE
CSS Modules support

### ISSUE THREAD

**Issue by a-rusak** [viljamis/vue-design-system#101]
It is nice to have a support for [Css modules](https://vue-loader.vuejs.org/guide/css-modules.html)
https://github.com/viljamis/vue-design-system/blob/2baa6e6341078b1cbdfa68b59e9663acb33e891b/build/utils.js#L20-L25
I've add into `options` next lines:
```javascript
modules: true,
localIdentName: "[local]_[hash:base64:8]"
```
from vue-loader documentation.
1. For dev mode (`npm run start`) css modules are not created
2. For build mode (`npm run build:system`) all css classes, no matter modules or not, are builded with hash.

**Comment by viljamis** [comment]
@a-rusak Sounds like a good idea, I think! Let me do some more experimenting around the subject and how it should be documented.

**Comment by viljamis** [comment]
I’ve added this information to the FAQ now: https://github.com/viljamis/vue-design-system/wiki/Frequently-Asked-Questions-(FAQ)#i-want-to-use-css-modules-are-those-supported

**Comment by otif11** [comment]
thanks for the info. @viljamis in the FAQ you can include the file path `vue-design-system/build/utils.js` and the commet 

> -     For dev mode (npm run start) css modules are not created
> -     For build mode (npm run build:system) all css classes, no matter modules or not, are builded with hash.

Thanks a lot @a-rusak

**Comment by schjetne** [comment]
I don't understand this comment:

> For dev mode (npm run start) css modules are not created

Does this mean that the reason my components are rendered without class names is because I am running in dev mode? If so, this should really be part of the FAQ. I've been trying to debug why my components don't have styles or even class names and I'm stumped.

**Comment by schjetne** [comment]
Ok I see now.

It's “possible” to “use” CSS modules, but in dev mode it's not doing anything useful, and in build mode it hashes all classes no matter if the style block is a CSS module block or not, equally as useful.

Is it possible to fix this somehow? Most of our components use CSS modules, but not all, which means the current answer to “Do you support CSS modules?” unfortunately is “No.”
