### ISSUE TITLE
REM vs px, incompatible with bootstrap 4

### ISSUE THREAD

**Issue by chenchenalex** [viljamis/vue-design-system#108]
Hi, I am running into an issue that I tried to integrate bootstrap 4 into vueds, but this error pops up: 

$input-height-inner: ($font-size-base * $input-btn-line-height) + ($input-btn-padding-y * 2) !default;
      Incompatible units: 'rem' and 'px'.

$font-size-base is 16px while bootstrap has replaced 16px to 1rem, any ideas on solving this one? thanks!

**Comment by chenchenalex** [comment]
Found one solution: change the value in font-size.yml to 1rem can solve the conflicts issue

**Comment by viljamis** [comment]
@chenchenalex Great!
