### ISSUE TITLE
Start the docs by default, not the app?

### ISSUE THREAD

**Issue by andywd7** [viljamis/vue-design-system#113]
Hi,

I'm trying to work out what to change to start the docs(:6060) up as the default page rather than the app(:8080)? Is it the port that needs to change or a config setting?

Thanks

**Comment by sdellis** [comment]
@andywd7 You can remove the `dev` command in the package.json `start` script. It will look like this:     `"start": "npm-run-all --parallel styleguide theo:onchange theo"`

It will hot-reload on any changes, but I'm not sure how to make it "auto launch" since that is a styleguidist/theo thing.

**Comment by andywd7** [comment]
Awesome! Thank you @sdellis and @viljamis.
