### ISSUE TITLE
SvgIcon component does not work in IE11

### ISSUE THREAD

**Issue by sdellis** [viljamis/vue-design-system#114]
I'm not sure what the browser support for VueDS is, but the SvgIcons do not work in ie11 because [ie11 does not support innerHTML on svg elements](https://github.com/vuejs/vue/issues/3722).

I tried to use the innersvg-polyfill, but it does not seem to be working (even in plain HTML without Vue).

I'm able to get it working using `img` tags with the svg as the `src`, but that means that icons cannot be filled dynamically with the `fill` prop.

**Comment by sdellis** [comment]
[This approach works in IE11](https://vuejs.org/v2/cookbook/editable-svg-icons.html). It will also be helpful for codesplitting/treeshaking steps discussed in #111 since the icons become components that are "imported" rather than "loaded".

**Comment by viljamis** [comment]
This has been fixed now in the latest 3.1.0 release.
