### ISSUE TITLE
Failed to compile in nuxt.js 2.0

### ISSUE THREAD

**Issue by colorfishmx** [viljamis/vue-design-system#119]
I'm getting errors when trying to execute npm run dev in my nuxt 2.0 project.
I've already followed the new instructions from the nuxt-design-system updated about 3 days ago.
And this is the log.

> Module Error (from ./node_modules/eslint-loader/index.js):
> 
> /path/vue-design-system/dist/system/system.js
>   1:1920   error  'e' is defined but never used         no-unused-vars
>   1:1933   error  Strings must use doublequote          quotes
>   1:2663   error  't' is defined but never used         no-unused-vars
>   1:2665   error  'e' is defined but never used         no-unused-vars
>   1:2667   error  'n' is defined but never used         no-unused-vars
>   1:2688   error  't' is defined but never used         no-unused-vars
>   1:2690   error  'e' is defined but never used         no-unused-vars
>   1:2775   error  'e' is defined but never used         no-unused-vars
>   1:2788   error  Strings must use doublequote          quotes
>   1:4430   error  't' is defined but never used         no-unused-vars
>   1:4432   error  'e' is defined but never used         no-unused-vars
>   1:4434   error  'n' is defined but never used         no-unused-vars
>   1:4873   error  Strings must use doublequote          quotes
>   1:4911   error  Strings must use doublequote          quotes
>   1:5278   error  't' is defined but never used         no-unused-vars
>   1:5280   error  'e' is defined but never used         no-unused-vars
>   1:5301   error  't' is defined but never used         no-unused-vars
>   1:5303   error  'e' is defined but never used         no-unused-vars
>   1:5324   error  't' is defined but never used         no-unused-vars
>   1:5326   error  'e' is defined but never used         no-unused-vars
>   1:5471   error  't' is defined but never used         no-unused-vars
>   1:5473   error  'e' is defined but never used         no-unused-vars
>   1:5942   error  'e' is defined but never used         no-unused-vars
>   1:5955   error  Strings must use doublequote          quotes
>   1:6421   error  't' is defined but never used         no-unused-vars
>   1:6423   error  'e' is defined but never used         no-unused-vars
>   1:7057   error  't' is defined but never used         no-unused-vars
>   1:7059   error  'e' is defined but never used         no-unused-vars
>   1:7061   error  'n' is defined but never used         no-unused-vars
>   1:7080   error  't' is defined but never used         no-unused-vars
>   1:7082   error  'e' is defined but never used         no-unused-vars
>   1:7163   error  't' is defined but never used         no-unused-vars
>   1:7165   error  'e' is defined but never used         no-unused-vars
>   1:7167   error  'n' is defined but never used         no-unused-vars
>   1:7836   error  '__VUE_SSR_CONTEXT__' is not defined  no-undef
>   1:8257   error  't' is defined but never used         no-unused-vars
>   1:8259   error  'e' is defined but never used         no-unused-vars
>   1:8261   error  'n' is defined but never used         no-unused-vars
>   1:8340   error  't' is defined but never used         no-unused-vars
>   1:8342   error  'e' is defined but never used         no-unused-vars
>   1:8344   error  'n' is defined but never used         no-unused-vars
>   1:8363   error  't' is defined but never used         no-unused-vars
>   1:8365   error  'e' is defined but never used         no-unused-vars
>   1:9743   error  't' is defined but never used         no-unused-vars
>   1:9745   error  'e' is defined but never used         no-unused-vars
>   1:9747   error  'n' is defined but never used         no-unused-vars
>   1:10274  error  't' is defined but never used         no-unused-vars
>   1:10276  error  'e' is defined but never used         no-unused-vars
>   1:10278  error  'n' is defined but never used         no-unused-vars
>   1:11028  error  'e' is defined but never used         no-unused-vars
>   1:11041  error  Strings must use doublequote          quotes
>   1:11587  error  't' is defined but never used         no-unused-vars
>   1:11589  error  'e' is defined but never used         no-unused-vars
>   1:11591  error  'n' is defined but never used         no-unused-vars
>   1:11670  error  't' is defined but never used         no-unused-vars
>   1:11672  error  'e' is defined but never used         no-unused-vars
>   1:15498  error  't' is defined but never used         no-unused-vars
>   1:15500  error  'e' is defined but never used         no-unused-vars
>   1:15502  error  'n' is defined but never used         no-unused-vars
>   1:16164  error  't' is defined but never used         no-unused-vars
>   1:16166  error  'e' is defined but never used         no-unused-vars
>   1:16185  error  't' is defined but never used         no-unused-vars
>   1:16187  error  'e' is defined but never used         no-unused-vars
>   1:16189  error  'n' is defined but never used         no-unused-vars
>   1:16270  error  't' is defined but never used         no-unused-vars
>   1:16272  error  'e' is defined but never used         no-unused-vars
>   1:16278  error  Extra semicolon                       semi

> ✖ 67 problems (67 errors, 0 warnings)
>   7 errors and 0 warnings potentially fixable with the `--fix` option.

**Comment by viljamis** [comment]
@colorfishmx Those are warning related to your ESlint config however, aren’t they? You should probably exclude the whole `node_modules` although I’m a little confused by `/path/vue-design-system/dist/system/system.js` there.
