### ISSUE TITLE
How to use v-model in sample code?

### ISSUE THREAD

**Issue by ftom2** [viljamis/vue-design-system#137]
Some components,  like custom input elements, use v-model and I'd like to display it in the sample code.

So I want to write a doc like this:

```
<docs>
     <AqInput label="danger" danger value="Something went wrong" v-model="input1" id="input-4" />
</docs>
```

input1 does not really exist on the model' it's just for the example, and of course it throws an error. Is it possible to define a mock v-model?

**Comment by viljamis** [comment]
@ftom2 Definitely possible. Please see Styleguidist’s docs for documenting components: https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md

**Comment by dabernathy89** [comment]
If anyone is googling and trying to figure this out, I went with using a mixin to store a variable in `data` that can be reused across examples:

https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-add-dummy-data-to-the-style-guide
