### ISSUE TITLE
How to use <router-link> in a pattern?

### ISSUE THREAD

**Issue by ftom2** [viljamis/vue-design-system#138]
I would like to create a sidebar component that uses `<router-link>`

But I get an error: 

`Unknown custom element: <router-link> - did you register the component correctly?`

How can I use `<router-link>`?

**Comment by viljamis** [comment]
@ftom2 Please see https://github.com/vue-styleguidist/vue-styleguidist/issues/131 (I think there are other closed issues with that same title too if it helps), this issue is related to the way Vue Styleguidist works.
