### ISSUE TITLE
Using vue-design-system to create a pure CSS stylesheet?

### ISSUE THREAD

**Issue by ducdebreme** [viljamis/vue-design-system#145]
I really like the vue-design-system - it is very elegant and made to the point. I have just a question: is it possible to use it in such a way that the resulting CSS can be used outside of a Javascript and Vuejs environment? 

I would like to export the resulting CSS to use it as a base of a Drupal theme. Would it still work, if I link the system.css in an oldfashioned way like this ?
 
` <link rel="stylesheet" type="text/css" href="system.css">`

**Comment by viljamis** [comment]
@ducdebreme definitely. `npm run build:system` does exactly that.
