### ISSUE TITLE
Only a few changes needed to make spacing rem-compatible

### ISSUE THREAD

**Issue by earlman** [viljamis/vue-design-system#181]
Hi,

I wanted to define my tokens by rem units, rather than by px. It took me a while to figure it out, but it came down to just changing a couple lines of code. I haven't submitted a pull request before, but I was wondering if there was interest in my solution

**Comment by benhartwigdesign** [comment]
I would be curious to know how to include rem units within the Vue Design System!

**Comment by earlman** [comment]
It's been a while since I worked with VDS, but I think that the only thing that prevented the system from compiling when I changed all the size tokens to REM was a couple small details in how they implemented the tokens in their mixins.

The first issue is where they use math in their inset-squish-space mixin. The second is where they use math in the styles for their docs. Basically, they used "1px" in the formula itself which is incompatible with REMs

You can see the changes I made here:
- https://github.com/earlman/vue-design-system/commit/9670b2aa51ed075ca72cebd3c6ac3e7100eb5ab9
- https://github.com/earlman/vue-design-system/commit/af75854097dc0f736636e606acc9883f4a9ac61f

and the fork:
- https://github.com/earlman/vue-design-system
