### ISSUE TITLE
Unclear "getting started" on an existing project

### ISSUE THREAD

**Issue by chinchang** [viljamis/vue-design-system#32]
I am a user with an existing Vue.js project with multiple components. How do I get started with using vue-design-system with my existing components?

Can't understand from the guide here -> https://github.com/viljamis/vue-design-system/wiki/getting-started

**Comment by viljamis** [comment]
@chinchang Thanks for creating the issue. Yes, there are currently no instructions related to that since I am still in the progress of writing and updating the documentation. Hoping to find time soon to do that!

**Comment by viljamis** [comment]
Will be making this a bit better today.

**Comment by viljamis** [comment]
@chinchang Hoping that this now provides better information on getting started: https://github.com/viljamis/vue-design-system/wiki/Getting-Started

### I added two important parts:

* Using Vue Design System in an existing project
* Using Design System as NPM Module

**Comment by viljamis** [comment]
Closing this one for now. Let me know if things are still unclear and I’ll work on that part of the docs more.

**Comment by chinchang** [comment]
Thanks @viljamis I'll try it out!

**Comment by viljamis** [comment]
@chinchang Just so that you know, there was an issue with one of the NPM dependencies in 1.3.1 so you’ll need to get the latest 1.3.2 release to try things out :-)
