### ISSUE TITLE
Any plan to support responsive views?

### ISSUE THREAD

**Issue by muhajirframe** [viljamis/vue-design-system#35]
Like this one here https://www.catalog.style/ ?

Really nice project by the way :)

**Comment by viljamis** [comment]
@muhajirframe I think that would be a cool and useful feature, but currently the project is using a customized version of Styleguidist to auto-generate the docs which doesn’t support that (at least right now).

I have plans to create simpler/more customizable Vue based styleguide generator for the project, but it’s a task which will require a lot of time and effort. I have done some work around it already, but it’s way too early to even call it a prototype. 

So while I’d love to see this kind of feature being added, it won’t happen very soon at least.

**Comment by viljamis** [comment]
I think I will close this one for now as I don’t see this becoming a feature of vueds any time in the near future. I think this should come from Styleguidist if/when they decide to do something like this.
