### ISSUE TITLE
1231313

### ISSUE THREAD

**Issue by kubasovp** [viljamis/vue-design-system#47]
74123тлщлио дщ о лд

**Comment by viljamis** [comment]
I am going to close this.

**Comment by kubasovp** [comment]
Sorry, I am just learning :)

**Comment by viljamis** [comment]
@kubasovp Oh, sorry for the rude answer! I thought was a form of spam :D

**Comment by kubasovp** [comment]
Do not worry, I'm not upset :)
I did not even understand how I was able to open this issue... :)
