### ISSUE TITLE
Any plan to support visualization of different component state?

### ISSUE THREAD

**Issue by MrJoeXu** [viljamis/vue-design-system#49]
I really dig the more systematic, process oriented approach offered by VueDS. Compared to [Storybook](https://storybook.js.org), I think VueDS is more opinionated and designer friendly. 

One thing that might be a deal-breaker for me is the ability the visualize different state of components (clicked/closed/hovering etc) and have a ActionLogger. Storybook provide this feature and make it more like a UI components playground. Is this something you guys are considering in the future?
And how do you position VueDS itself comparing to Storybook or Patternplate?

**Comment by viljamis** [comment]
@MrJoeXu Vue Design System uses currently a customized version of Vue Styleguidist for the Style Guide part which already supports something similar. 

You can for example define multiple examples for any component in markdown format in the component’s `<docs>` section. A simplified example from Styleguidist’s docs:

![Styleguidist Example](https://camo.githubusercontent.com/76ad6e4b0b94d33b3430db33d7dd03029fe1fa67/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f74595644444c594d6f70554c694333685f507769773639525a3835674c5370515159683563704f67667659794d717a5a6f395a386370484c695a374a742d4b706e7966615f534e705a5377746f6b515354493731723964395171483462796d787265564f5930756e764b4564306171435935594c437773465f6f5376433773485045484b7353774a4c733446626e656f586436655a5134465f4b763745435f73595463314b65756f535a7262726f683552776c4677377432695a4468516e703472562d53546339706c4836684c67315179506d3065685636433534737a67536f69355055575854694962473633444e58546e337a697a6b4f4c706b2d424f452d455f7568526d4c694e626167675672666a772d7a496e7157676f75617156326651664c6b575073375736534a486e38496153396a4b564a424635434e3672763965514e73377346725f75395a77427655377956414a7132674c7241443033334a64486a782d4c5a6251495f6b434776585639387945503743324f487349782d4954386e39306e62466e41587037746c41632d6d475165556e4549646e6665344764494c454450357459506d752d6e4b654e37744c365f452d6b704e386f49543674646d32794345697668517836436376444a6c704149473965475764757774663263324b66783655306b3462576743696437585f33394b6b67446d4362554d743266644d4d666344564872474f4d57694f567a426246754b784d6249786264374a3074795f5a4b4b613864464966684c59645574524b3462436a66375a4b49714e55793977774b593d77313630302d68373934)

See the documentation for Vue Styleguidist: https://github.com/vue-styleguidist/vue-styleguidist

Here’s also React Styleguidist’s explanation on the differences between Storybook and it: https://react-styleguidist.js.org/docs/cookbook.html#whats-the-difference-between-styleguidist-and-storybook

I hope this helps.

**Comment by viljamis** [comment]
@MrJoeXu I will try to provide an example of this in 2.0.0 release that I’m working on.

**Comment by viljamis** [comment]
Example is already in https://github.com/viljamis/vue-design-system/pull/56

**Comment by MrJoeXu** [comment]
Sweet! This is really helpful!

**Comment by viljamis** [comment]
Released in [Vue Design System 2.0.0](https://github.com/viljamis/vue-design-system/releases/tag/2.0.0). For a live example see the demo docs: https://vueds.com/example/#!/Elements?id=forminput
