### ISSUE TITLE
A simple guide to update the version

### ISSUE THREAD

**Issue by chenxeed** [viljamis/vue-design-system#62]
Hi,

I appreciate the constant updates to the repo to make it better.

Just a suggestion that I believe a simple guide on how to upgrade the previous version to the latest version will help us too. Thank you again for this!

**Comment by viljamis** [comment]
@chenxeed Yes, very good idea 👍

**Comment by viljamis** [comment]
@chenxeed I think the easiest solution would be to have a command line interface for updating. I will close this issue and the discussion can continue in: https://github.com/viljamis/vue-design-system/issues/83
