### ISSUE TITLE
[Question] Doc style using tokens?

### ISSUE THREAD

**Issue by markokajzer** [viljamis/vue-design-system#76]
Hello! Thank you so much for your great work with this project!

Am I right in the assumption that changing values in `src/tokens` folder, like `font_size_xx_large`, has an impact on the styling of the docs itself, as they are using the same variables? Shouldn't the docs style and the style of the design system be separate? Or maybe I am doing something wrong here?

A small hint in the right direction would be much appreciated. If it should be indeed separated, I could provide a pull request, as I made the necessary changes to my own project already.

**Comment by paulgeisler** [comment]
You definitely doing something wrong here.

**Comment by viljamis** [comment]
@markokajzer Hey! This is on purpose, but I’m planning on making it opt-in rather than opt-out in the next version. 

Currently, you should be able to just remove or comment out this line to disable most of this: https://github.com/viljamis/vue-design-system/blob/master/docs/docs.styles.scss#L6
