### ISSUE TITLE
Show both VUE and HTML markup

### ISSUE THREAD

**Issue by timhartmann** [viljamis/vue-design-system#77]
I love your tool a lot to create a solid design system. I like the concept, but I have a huge problem. So I would use your tool to create a design system for a leading news platform in germany. Finally my team will use for the website something more static instead of vue. So I need a static documentation in your tool - the compiled html like in Pattern Lab.

In Pattern Lab I write my component in mustache, but I can take a look at the compiled html in the frontend too. This is a must have for my team. Does it possible to get the compiled html in the frontend? 

I **do not** want to do it like this example here:
![bildschirmfoto 2018-05-04 um 17 45 31](https://user-images.githubusercontent.com/986401/39637339-f84654de-4fc2-11e8-964b-1b2b2a8cbf52.png)

I would like it more like this here:
![bildschirmfoto 2018-05-04 um 17 50 47](https://user-images.githubusercontent.com/986401/39637561-b3199104-4fc3-11e8-8507-2894640c7236.png)

![bildschirmfoto 2018-05-04 um 17 50 17](https://user-images.githubusercontent.com/986401/39637536-a2000150-4fc3-11e8-8936-859edd5db774.png)

**It is so important. Without this feature I can not use it for my team and the design system.**

**Comment by viljamis** [comment]
@timhartmann Thanks for the feedback and ideas Tim. I understand that this is an important feature and something I’ve been also pondering in the past, but currently Vue Design System doesn’t support it out of the box.

**Comment by timhartmann** [comment]
What do you think about the solution by Rafael @viljamis?

https://github.com/vue-styleguidist/vue-styleguidist/issues/126

I am not sure what I must do to change the output in the editor..

**Comment by rafaesc** [comment]
Hi @timhartmann

I think that the solution mentioned above still is not possible to integrate yet in vds, first, this issue should be done
https://github.com/viljamis/vue-design-system/issues/75

I hope that this week can close. Regards

**Comment by viljamis** [comment]
@timhartmann This is under work now and there’s a working version already in: https://github.com/viljamis/vue-design-system/pull/85 (although at this point I wouldn’t yet use it as it’s only the functionality, no UI for it yet)

**Comment by viljamis** [comment]
Current status: 
<img width="1124" alt="screenshot 2018-06-01 11 40 32" src="https://user-images.githubusercontent.com/671836/40831096-be4f158e-6590-11e8-8689-88fa8d7f4721.png">

**Comment by viljamis** [comment]
@rafaesc working prototype: 
![jun-01-2018 14-47-28](https://user-images.githubusercontent.com/671836/40839451-4a96dc06-65ab-11e8-96b5-1c7f6485cad1.gif)

**Comment by rafaesc** [comment]
Awesome work @viljamis!

**Comment by viljamis** [comment]
This is now merged to master and about to release in 3.2.0
