### ISSUE TITLE
Using custom font after the system built

### ISSUE THREAD

**Issue by MrJoeXu** [viljamis/vue-design-system#78]
I used a custom font locally and load them according to this [commit](https://github.com/viljamis/vue-design-system/commit/a7b3badb618fb5e0e1c999940b8ea82e86aea190). It works well inside the doc. 

But once I did `npm run build:system` and install the design system as a seperate npm module in my main app, the custom font wasn't loaded in any of the `design-system`'s component. Is this a known limitation of the system, or is there some extra steps I have to follow?

**Comment by viljamis** [comment]
@MrJoeXu It isn’t really a limitation. The static assets just aren’t copied by default when running `build:system`.

I modified that branch a little and added a little more functionality. See this commit: https://github.com/viljamis/vue-design-system/commit/e7eea29327b54520df8c8eaca26294f52d4159de

With those changes, you can run `npm run build:system` and it’ll copy the fonts over as well. Once the build is complete, you just need to make sure to import the fonts correctly in your projects. So for example importing the fonts in your `main.js`:

```js
import system from 'vue-design-system'
import 'vue-design-system/dist/system/system.css';
import 'vue-design-system/dist/system/fonts/fonts.css';
Vue.use(system)
```

And making sure that your Webpack config has the necessary rules to load font files (you might already have something like this, but if not, Webpack will throw you an error):

```js
{
    test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
    loader: "file-loader",
    options: {
        limit: 10000,
    },
}
```

**Comment by viljamis** [comment]
@MrJoeXu I’ve release a new version (2.1.4) where the static assets are now copied by default when build a lib too. If you already did those changes, no need up update though.
