### ISSUE TITLE
Parser changes are breaking new created projects

### ISSUE THREAD

**Issue by omarsotillo** [viljamis/vue-design-system#79]
see: https://github.com/vuejs/component-compiler-utils/issues/14

**Comment by viljamis** [comment]
@omarsotillo Looking into this now.

**Comment by viljamis** [comment]
@omarsotillo fixed in 2.1.4

**Comment by viljamis** [comment]
You should delete node_modules and package-lock just in case and then do a fresh npm install

**Comment by omarsotillo** [comment]
Awesome! 🤗 Just wanted to let you know in case someone asks you again! I fixed myself ☺

**Comment by viljamis** [comment]
👍
