### ISSUE TITLE
webFontLoader works with docs but not with system build

### ISSUE THREAD

**Issue by sdellis** [viljamis/vue-design-system#88]
Hi, this seems to be a bug. I can see that the <heading> element displays the correct font (Fire Sans) out of the box in the "living documentation" pages. However, the font is not getting built into the system build, so when I try to use it via `npm install` in another app, the <heading> component font falls back to Helvetica because it can't load the Google font. I've tried with typekit as well and have the same issue.

**Comment by sdellis** [comment]
This is "resolved" in the sense that I just had to add `import WebFontLoader from "@/utils/webFontLoader"` to the top of the system.js entry file.

**Comment by viljamis** [comment]
@sdellis Hey! Just returned from a 5 week “offline” trip, hence the little delay here. Need help still?

**Comment by sdellis** [comment]
@viljamis thank you for the follow up. I'm good now, but you may want to add that import to the `system.js` file in a future release. Otherwise, the css will reference the font correctly, but the fonts won't load when distributing the design system via npm.
